{
 "title": "Power",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "plug",
    "label": "Plug ID",
    "query": {
     "query": "label_values(plug_current,plug_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Plug $plug", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "plug" },
  {
   "title": "Voltage",
   "type": "stat",
   "description": "Current measured",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plug_voltage{plug_id=\"$plug\"}",
     "legendFormat": "Voltage plug $plug"
    }
   ]
  },
  {
   "title": "Current",
   "type": "stat",
   "description": "Current measured",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plug_current{plug_id=\"$plug\"}",
     "legendFormat": "Current plug $plug"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "description": "Current measured",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plug_power{plug_id=\"$plug\"}",
     "legendFormat": "Voltage plug $plug"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Plug status",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "plug_active{plug_id=\"$plug\"}",
     "legendFormat": "Status plug $plug"
    }
   ]
  },
  {
   "title": "Measuring time",
   "type": "stat",
   "description": "Time required to calculate power",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "measure_time", "legendFormat": "Measuring time" }
   ]
  }
 ]
}