version: '3.8'

services:
  prometheus1:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped

  grafana1:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards/:/var/lib/grafana/dashboards
    restart: unless-stopped
