#!/bin/sh
set -e

VENV_DIR=/usr/share/spear/venv

if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
fi

$VENV_DIR/bin/pip install --upgrade pip
$VENV_DIR/bin/pip install -r /usr/share/spear/requirements.txt

systemctl daemon-reload
systemctl enable spear.service

exit 0
