name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f webservice/requirements.txt ]; then pip install -r webservice/requirements.txt; fi
          pip install pytest pytest-cov codecov

      - name: Run tests with coverage
        run: |
          make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
          verbose: true

  arduino-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - arduino:avr:uno
          - arduino:avr:mega
          - arduino:avr:nano

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install board core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile main sketch
        run: |
          arduino-cli compile \
            --fqbn ${{ matrix.board }} \
            --output-dir build/${{ matrix.board }} \
            --libraries ./Arduino/libraries \
            ./Arduino/multi_ac_current_measure

#      - name: Upload HEX artifacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: hex-${{ matrix.board }}
#          path: build/${{ matrix.board }}/*.hex
#          retention-days: 7

